apiVersion: v1
kind: ReplicationController
metadata:
  name: client
  labels:
    name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
      - name: client
        image: seriousben/ocr-feed-client:latest
        ports:
        - containerPort: 4000
          name: client
        env:
        - name: API_HOST
          value: http://server.ocr-feed.seriousben.com
        - name: FASTBOOT_API_HOST
          value: http://server
