apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.5.4
          ports:
            - containerPort: 5432
