apiVersion: v1
kind: ReplicationController
metadata:
  name: server
  labels:
    name: server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: ocr-feed-server
        image: seriousben/ocr-feed-server:latest
        ports:
        - containerPort: 3000
          name: server
        env:
        - name: PG_CONNECTION_STRING
          value: postgres://postgres@postgres.default:5432/postgres
